#!/bin/sh
# sassc gate: links sassc against OUR libsass and runs the sass-spec harness.
#
# Usage:
#   tool/build-sassc.sh            # build only; prints the harness command
#   tool/build-sassc.sh --run [spec-subpath...]
#                                  # build, then run the harness (full suite
#                                  # when no subpath is given)
#
# Environment:
#   PROFILE=release                # use the release cdylib (default: debug)
#
# This mirrors sassc's `BUILD=shared` flow (`build-shared` in sassc/Makefile:
# compile sassc.c against the lib tree's include/, link -lsass with an rpath)
# minus its in-tree libsass build — our library comes from cargo, so the
# `libsass-shared` sub-make has nothing to do here. All outputs live under
# target/sassc-gate/ (ephemeral, never committed).
#
# See docs/plans/libsass.md step 5.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PROFILE="${PROFILE:-debug}"
OUT="$ROOT/target/sassc-gate"
OS="$(uname -s)"

if [ "$PROFILE" = "release" ]; then
    CARGO_PROFILE_FLAG="--release"
else
    CARGO_PROFILE_FLAG=""
fi

# 1. Our library (cdylib).
# shellcheck disable=SC2086
cargo build -p rust-sass-libsass $CARGO_PROFILE_FLAG

# 2. Assemble the lib tree sassc expects: include/ + lib/libsass.{dylib,so}.
LIB_SRC=""
if [ -f "$ROOT/target/$PROFILE/libsass.dylib" ]; then
    LIB_SRC="$ROOT/target/$PROFILE/libsass.dylib"
elif [ -f "$ROOT/target/$PROFILE/libsass.so" ]; then
    LIB_SRC="$ROOT/target/$PROFILE/libsass.so"
else
    echo "error: no shared libsass in $ROOT/target/$PROFILE" >&2
    exit 1
fi
mkdir -p "$OUT/lib" "$OUT/include"
cp "$LIB_SRC" "$OUT/lib/"
rm -rf "$OUT/include"
cp -r "$ROOT/libsass/include" "$OUT/include"

# Hermeticity: macOS ld records the library's own install-name (which cargo
# sets to an absolute target/debug/deps path), ignoring -L/rpath — without
# this the binary would silently track whatever cargo last built instead of
# this tree. Rewrite the copy's ID to @rpath so the rpath below governs.
# (Linux needs nothing: our cdylib carries no SONAME, so -l records the bare
# name and the rpath resolves it to this tree.)
if [ "$OS" = "Darwin" ]; then
    install_name_tool -id @rpath/libsass.dylib "$OUT/lib/$(basename "$LIB_SRC")"
fi

# 3. Compile sassc.c (flags mirror the Makefile: -Wall -O2, libc++ on Darwin
# at link time).
SASSC_VERSION="$(git -C "$ROOT/sassc" describe --tags 2>/dev/null || echo rust-sass-libsass)"
if [ "$OS" = "Darwin" ]; then
    STDLIB_FLAGS="-stdlib=libc++"
else
    STDLIB_FLAGS=""
fi
# shellcheck disable=SC2086
cc -Wall -O2 \
    -DSASSC_VERSION="\"$SASSC_VERSION\"" \
    -I"$OUT/include" \
    -c "$ROOT/sassc/sassc.c" -o "$OUT/sassc.o"
# shellcheck disable=SC2086
cc $STDLIB_FLAGS \
    -o "$OUT/sassc" "$OUT/sassc.o" \
    -L"$OUT/lib" -lsass \
    "-Wl,-rpath,$OUT/lib"

# 4. Harness wrapper: strip the dart-sass-only flags the harness prepends
# for --impl dart-sass (sassc's getopt rejects them; the comparison still
# expects dart-style ASCII output, which our library renders — plan G23),
# and force Expanded output: the harness passes no --style flag, so the
# binary default governs — since the NESTED integration that default is
# real libsass-nested, while every golden encodes Dart expanded (plan D5
# amended; nested rendering itself is covered by the node-sass gate +
# contract tests, not here).
cat > "$OUT/sassc-spec.sh" <<EOF
#!/bin/sh
# Generated by rust-sass-libsass-tests/tool/build-sassc.sh — do not edit.
SASSC="\${SASSC_BIN:-$OUT/sassc}"
args="-t expanded"
for a in "\$@"; do
  case "\$a" in
    --verbose|--no-unicode|--no-color) ;;
    *) args="\$args '\$a'" ;;
  esac
done
eval "exec '\$SASSC' \$args"
EOF
chmod +x "$OUT/sassc-spec.sh"

echo "sassc gate built: $OUT/sassc"
"$OUT/sassc" -v
echo "harness: npm run sass-spec -- --command $OUT/sassc-spec.sh --impl dart-sass [spec-subpath]  (cwd: sass-spec/)"

if [ "${1:-}" = "--run" ]; then
    shift
    cd "$ROOT/sass-spec"
    npm run sass-spec -- --command "$OUT/sassc-spec.sh" --impl dart-sass "$@"
fi
