// Copyright 2016 Google Inc. Use of this source code is governed by an
// MIT-style license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.
//
// Ported and rearchitected for Rust by Luka Zakrajsek.

// dart-source: lib/src/ast/node.dart
// go-source: go/sasscommon/ast_node.go

use crate::common::exception::SassResult;
use crate::common::file_span::FileSpan;

/// A node in an abstract syntax tree.
///
/// Mirrors Dart's `AstNode`: not used for visitor dispatch (that is enums +
/// `match` in Rust) — it exists so heterogeneous node types can report their
/// span. The `toString` debugging note from Dart applies equally: string
/// forms reflect source text but are unstable and must not be used to
/// generate Sass source.
pub trait AstNode<'parse> {
    /// The source span associated with the node.
    ///
    /// Indicates where in the source Sass or SCSS stylesheet the node was
    /// defined.
    fn span(&self) -> SassResult<FileSpan<'parse>>;
}

/// An [`AstNode`] that exposes a single span generated by a callback.
///
/// Mirrors Dart's `AstNode.fake` (`_FakeAstNode`): several APIs take nodes
/// instead of spans because computing spans eagerly can be expensive, so this
/// lets arbitrary lazily-computed spans flow through those callbacks.
pub struct FakeAstNode<'parse> {
    callback: Box<dyn Fn() -> SassResult<FileSpan<'parse>> + 'parse>,
}

impl<'parse> FakeAstNode<'parse> {
    /// Returns a node with no data whose span is generated by `callback`.
    ///
    /// Mirrors Dart's `AstNode.fake(callback)`.
    pub fn new<F>(callback: F) -> Self
    where
        F: Fn() -> SassResult<FileSpan<'parse>> + 'parse,
    {
        FakeAstNode {
            callback: Box::new(callback),
        }
    }
}

impl<'parse> AstNode<'parse> for FakeAstNode<'parse> {
    fn span(&self) -> SassResult<FileSpan<'parse>> {
        (self.callback)()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::common::exception::SassError;
    use crate::common::source_span_file_source::FileSource;
    use bumpalo::Bump;

    #[test]
    fn test_fake_ast_node_span() {
        let arena = Bump::new();
        let fs = FileSource::new_in(&arena, "hello", None);
        let span = FileSpan::new(Some(fs), 0, 5);
        let node = FakeAstNode::new(move || Ok(span));
        let got = node.span().unwrap();
        assert_eq!(got.text(), "hello");
    }

    #[test]
    fn test_fake_ast_node_span_error() {
        let node = FakeAstNode::new(|| {
            Err(Box::new(SassError::Script {
                message: "test".into(),
                argument_name: None,
            }))
        });
        assert!(node.span().is_err());
    }

    #[test]
    fn test_fake_ast_node_is_ast_node() {
        let arena = Bump::new();
        let fs = FileSource::new_in(&arena, "x", None);
        let node: Box<dyn AstNode> =
            Box::new(FakeAstNode::new(move || Ok(FileSpan::new(Some(fs), 0, 1))));
        let _ = node.span().unwrap();
    }
}
